version: '3.7'
services:
  frontend:
    container_name: frontend
    image: htrvolker/cne-fp-frontend:latest
    build: ./01_frontend
    environment:
      SECRET_KEY: ${SECRET_KEY}
    ports:
    - published: 5000
      target: 5000
  gateway:
    container_name: gateway
    image: htrvolker/cne-fp-gateway:latest
    build: ./02_gateway
    ports:
    - target: 6000
      published: 6000
  tickets:
    container_name: tickets
    image: htrvolker/cne-fp-tickets:latest
    build: ./03_tickets
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
    - published: 7000
      target: 7000
  database:
    container_name: database
    image: htrvolker/cne-fb-database:latest
    build: ./04_database
    volumes:
    - type: volume
      source: database_vol
      target: /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: helpqueue
    ports:
    - published: 3306
      target: 3306
volumes:
  database_vol: