version: '3.8'
services:
  frontend:
    container_name: frontend
    image: htrvolker/cne-fp-frontend:latest
    build: ./frontend
    ports:
    - published: 5000
      target: 5000
  trainers:
    container_name: trainers
    image: htrvolker/cne-fp-trainers:latest
    build: ./trainers
    ports:
    - published: 5500
      target: 5500
  intakes:
    container_name: intakes
    image: htrvolker/cne-fp-intakes:latest
    build: ./intakes
    ports:
    - published: 5501
      target: 5501
  backend:
    container_name: backend
    image: htrvolker/cne-fp-backend:latest
    build: ./backend
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
    - published: 6000
      target: 6000
  database:
    container_name: database
    image: mysql:5.7
    volumes:
    - type: volume
      source: database_vol
      target: /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: trainingtools
    ports:
    - published: 3306
      target: 3306
volumes:
  database_vol: