apiVersion: v1
kind: Service
metadata:
  name: tickets
spec:
  selector:
    app: tickets
  ports:
  - protocol: TCP
    port: 7000
    targetPort: 7000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets
  labels:
    app: tickets
spec:
  replicas: 1      
  selector:
    matchLabels:
      app: tickets
  template:
    metadata:
      labels:
        app: tickets
    spec:
      hostname: tickets
      containers:
      - name: tickets
        image: htrvolker/cne-fp-tickets:latest
        ports:
        - containerPort: 7000
